### ISSUE TITLE
Path problem after fresh installation with rvm and ruby 1.9.3

### ISSUE THREAD

**Issue by MarceloEmmerich** [bbcoimbra/system-getifaddrs#1]
I have a fresh install of ruby 1.9.3 through rvm. I install system-getifaddr and run this test:

 1 # test.rb
 2 require "pp"
 3 require "system/getifaddrs"
 4 pp System.get_ifaddrs

The I get the folowing error:

/Users/Marcelo/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- /Users/Marcelo/.rvm/gems/ruby-1.9.3-p194/gems/system-getifaddrs-0.1.2/lib/system/../rb_getifaddrs (LoadError)

I can fix the problem temporarily by removing the ".." from
/Users/Marcelo/.rvm/gems/ruby-1.9.3-p194/gems/system-getifaddrs-0.1.2/lib/system/getifaddrs.rb.

System is MacOS X 10.7.3

Thanks,
Marcelo

**Comment by wtn** [comment]
This issue was reintroduced [here](https://github.com/bbcoimbra/system-getifaddrs/commit/8386b3e4919f11dbf9209c3b2ecd397c86809f50#diff-c54c20d11c2dbba214c326fd11229892e08f809601f75335bcedddbbc6b36013), resulting in the following exception:

```
LoadError: cannot load such file -- rb_getifaddrs
```

**Comment by wtn** [comment]
Please reopen this issue.
